# Import Libraries

In [1]:
import pandas as pd

# Load CSV and Explore Data

In [2]:
# Destacar que se me mostraba este error - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte
# Error solucionado añadiendo: encoding = 'ISO-8859-1'

data = pd.read_csv('GSAF5.csv', encoding = 'ISO-8859-1')
data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [3]:
# Al ser muchas columnas (24) y muchísimas filas (5992) no todas se reflejan en la previsualización. 
# Quiero ver todas las columnas, para lo cual utilizo lo siguiente:

pd.options.display.max_columns = None

# Para las filas también usaría lo mismo, pero son tantas que hace que se me ralentice todo al cargar.
# Por tanto lo que haré será ver las primeras 50 filas para tener una visión mayor.

data.head(50)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,NaN,"West Australian, 9/15/2016",2016.09.15.R-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.15.R,2016.09.15.R,5988,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,60s,Minor injury to arm,N,15h15,3' to 4' shark,"News4Jax, 9/11/2016",2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.11,2016.09.11,5987,NaN,NaN
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14h30,"Tiger shark, 10?","Hawaii News Now, 9/7/2016",2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.07,2016.09.07,5986,NaN,NaN
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,50,FATAL,Y,15h40,NaN,"TVANouvelles, 9/6/2016",2016.09.06-Jewell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.06,2016.09.06,5985,NaN,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,Late afternoon,NaN,"C. Creswell, GSAF",2016.09.05.b-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.b,2016.09.05.b,5984,NaN,NaN
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,NaN,"No inury, board broken in half by shark",N,Late afternoon,NaN,"Perth Now, 9/5/2016",2016.09.05.a-Penman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.a,2016.09.05.a,5983,NaN,NaN
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,9,Foot bitten,N,NaN,NaN,"Orlando Sentinel, 9/7/2016",2016.09.04-Moore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.04,2016.09.04,5982,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark,"R. Collier, GSAF",2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.01,2016.09.01,5981,NaN,NaN
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15h00,"Bull shark, 6'","News Channel 8, 8/30/16",2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.b,2016.08.29.b,5980,NaN,NaN
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,37,Minor injury to ankle,N,14h00,NaN,"News Channel 8, 8/30/16",2016.08.29.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.a,2016.08.29.a,5979,NaN,NaN
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m","LaDepeche, 8/29/2016",2016.08.27-Chardard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.27,2016.08.27,5978,NaN,NaN
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,49,Minor injury to ankle,N,16h00,NaN,"First Coast News, 7/25/2016",2016.08.25-Cassetty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.25,2016.08.25,5977,NaN,NaN
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN,"ABC, 8/11/2016",2016.08.07-Stoch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.07,2016.08.07,5976,NaN,NaN
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'","SUP, 8/9/2015",2016.08.06-Baxter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.06,2016.08.06,5975,NaN,NaN
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark,"News 965, 8/5/2016",2016.06.04-Tyler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.04,2016.08.04,5974,NaN,NaN
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,40,Lacerations to right hand,N,11h30,Blue shark,"Informacion.es, 7/29/2016",2016.07.29-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.29,2016.07.29,5973,NaN,NaN
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,72,Lacerations to leg,N,NaN,NaN,"Klassick, 7/28/2016",2016.07.28.R-Franz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28.R,2016.07.28.R,5972,NaN,NaN
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,NaN,"No injury, shark nudged kayak repeatedly",N,NaN,White shark,"ABC Australia, 7/28/2016",2016.07.28-Watkins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28,2016.07.28,5971,NaN,NaN
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,43,Laceration to left forearm PROVOKED INCIDENT,N,NaN,"Nurse shark, 4'","Tampa Bay Times, 7/27/2016",2016.07.27-Sapp.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.27,2016.07.27,5970,NaN,NaN
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12h00,NaN,"Gold Coast Bulletin, 7/28/2016",2016.07.26-Ballina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.26,2016.07.26,5969,NaN,NaN
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,29,Lacerations to left leg,N,19h05,NaN,"Japan Times, 7/25/2016",2016.07.24-Japan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.24,2016.07.24,5968,NaN,NaN
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN,"C. Black, GSAF",2016.07.23.b-Critchlow.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.b,2016.07.23.b,5967,NaN,NaN
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,NaN,Lacerations to face and right leg,N,NaN,"Bull shark, 6'","KWTX, 7/23/2016",2016.07.23.a-Cutbirth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.a,2016.07.23.a,5966,NaN,NaN
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,31,Laceration to left calf from hooked shark PROV...,N,After noon,"reef shark, 1m","Nine News, 7/20/2016",2016.07.20-Burck.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.20,2016.07.20,5965,NaN,NaN
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,NaN,"No injury, shark bit trolling motor",N,NaN,"Tiger shark, 10'","Al.com, 7/19/2016",2016.07.17-Gulf.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.17,2016.07.17,5964,NaN,NaN
30,2016.07.16.b,16-Jul-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,female,F,9,Minor injury to leg,N,1300,NaN,"Orlando Sentinel, 7/21/2016",2016.07.16.b-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.16.b,2016.07.16.b,5963,NaN,NaN
31,2016.07.16.a,16-Jul-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",NaN,female,F,11,Minor injury to toes,N,11h00,NaN,"Orlando Sentinel, 7/21/2016",2016.07.16.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.16.a,2016.07.16.a,5962,NaN,NaN
32,2016.07.15,15-Jul-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",Swimming,male,M,NaN,Puncture wounds to foot,N,NaN,NaN,"C. Creswell, GSAF",2016.07.14-MyrtleBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.15,2016.07.15,5961,NaN,NaN
33,2016.07.14.4,Reported 14-Jul-2016,2016,Unprovoked,BAHAMAS,NaN,Tiger Beach,Scuba Diving,Michael Dornellas,M,NaN,Face bruised when partly blind shark collided ...,N,NaN,"Lemon shark, 9'","GrindTV, 7/14/2016",2016.07.14.R-TigerBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.14.R,2016.07.14.4,5960,NaN,NaN
34,2016.07.08.R,Reported 08-Jul-2016,2016,Unprovoked,SPAIN,Canary Islands,"Las Teresitas, Tenerife",Wading,female,F,10,"5 tiny puncture marks to lower leg, treated wi...",N,NaN,Angel shark,La Opinion de Tenerife,2016.07.08.R-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.08.R,2016.07.08.R,5959,NaN,NaN
35,2016.07.08,08-Jul-16,2016,Boat,USA,California,"Capitola, Santa Cruz County",Fishing for squid,Mark Davis,M,NaN,"No injury. Hull bitten, tooth fragment recovered",N,NaN,White shark,"R. Collier, GSAF",2016.07.08-CapitolaBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.08,2016.07.08,5958,NaN,NaN
36,2016.07.07.b,07-Jul-16,2016,Provoked,USA,Massachusetts,"Off Gloucester, Essec County",Fishing,Roger Brissom,M,59,Fin of hooked shark injured fisherman's forear...,N,10h00,dogfish shark,Salem News 7/8/2016,2016.07.07.b-Brissom.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.07.b,2016.07.07.b,5957,NaN,NaN
37,2016.07.07.a,07-Jul-16,2016,Boat,USA,California,"Off Palos Verdes peninsula, Los Angeles County",Fishing for sharks,24' boat Shark Tagger Occupant Keith Poe,M,NaN,"No injury. Hull bitten, tooth fragment recovered",N,NaN,White shark,"R. Collier, GSAF",2016.07.07.a-PoeBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.07.a,2016.07.07.a,5956,NaN,NaN
38,2016.07.06,06-Jul-16,2016,Unprovoked,USA,Florida,"Melbourne Beach, Brevard County",Swimming,female,F,42,"Buttocks, thigh, left hand & wrist injured",N,14h30 / 15h30,NaN,"Florida Today, 7/6/2016",2016.07.06-Njwoman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.06,2016.07.06,5955,NaN,NaN
39,2016.07.04,04-Jul-16,2016,Provoked,AUSTRALIA,Queensland,Palm Cove,Fishing,Nathan Oliver,M,34,Right thigh injured by hooked pregnant female ...,N,22h00,Tawny nurse shark,"Cairns Post, 7/9/2016",2016.07.04-Oliver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.04,2016.07.04,5954,NaN,NaN
40,2016.06.27,27-Jun-16,2016,Unprovoked,USA,South Carolina,Sullivan's Island,NaN,male,M,35,Minor injury,N,16h20,3' to 4' shark,"C. Creswell, GSAF",2016.06.27-Sullivans.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.27,2016.06.27,5953,NaN,NaN
41,2016.06.25,25-Jun-16,2016,Unprovoked,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",Surfing,male,M,11,Foot injured,N,14h34,NaN,"C. Creswell, GSAF",2016.06.25-AtlanticBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.25,2016.06.25,5952,NaN,NaN
42,2016.06.24,24-Jun-16,2016,Unprovoked,COLUMBIA,Isla Provedencia,NaN,Scuba Diving,Arturo Velez,M,59,Severe bite to right hand,N,11h00,"Caribbean reef shark, 4.5'",Dr. A. Velez,2016.06.24-Velez.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.24,2016.06.24,5951,NaN,NaN
43,2016.06.23,23-Jun-16,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,Ryspunt,Spearfishing,male,M,43,Injuries to left leg & right hand,N,NaN,White shark,"News 24, 6/23/2016",2016.06.23-Rysport.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.23,2016.06.23,5950,NaN,NaN
44,2016.06.21.b,21-Jun-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",Floating,Jeff Schott,M,42,Lacerations and punctures to foot,N,15h25,3' to 5' shark,"C. Creswell, GSAF",2016.06.21.b-Schott.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.21.b,2016.06.21.b,5949,NaN,NaN
45,2016.06.21.a,21-Jun-16,2016,Unprovoked,USA,Florida,"Pelican Beach Park, Satellite Beach, Brevard C...",Wading,male,M,NaN,Injuries to right calf,N,14h55,NaN,"Florida Today, 6/22/2016",2016.06.21.a-SatelliteBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.21.a,2016.06.21.a,5948,NaN,NaN
46,2016.06.15.b,15-Jun-16,2016,Unprovoked,USA,Hawaii,"Kalapaki Beach, Kauai",Surfing,male,M,NaN,Single puncture wound to arm,N,06h00,3' to 4' shark,"West Hawaii Today, 6/16/2016",2016.06.15.b-Kauai.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.15.b,2016.06.15.b,5947,NaN,NaN
47,2016.06.15.a,15-Jun-16,2016,Provoked,AUSTRALIA,Western Australia,Coral Bay,Spearfishing,Brad Vale,M,19,No injury but shark punctured his wetsuit afte...,N,NaN,5' shark,"Perth Now, 6/16/2016",2016.06.15.a-Vale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.15.a,2016.06.15.a,5946,NaN,NaN
48,2016.06.14,14-Jun-16,2016,Unprovoked,USA,Texas,"Pirates Beach, Galveston",Floating in tube,Marin Alice Melton,F,6,Injury to lower leg,N,17h30,3' to 4' shark,"Click2Houston, 6/14/2016",2016.06.14-Melton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.14,2016.06.14,5945,NaN,NaN
49,2016.06.11,11-Jun-16,2016,Unprovoked,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",Standing,Dillon Bowen,M,19,Laceration to wrist,N,15h00,3' shark,"C. Creswell, GSAF",2016.06.11-Bowen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.06.11,2016.06.11,5944,NaN,NaN

# Explore DataFrame

## Shape, Columns, Variable Types

In [4]:
# Lo primero, conocer el shape del que partimos.

data.shape

(5992, 24)

In [5]:
# Vemos 5992 rows y 24 columnas.

In [6]:
# A continuación, vamos a ver una info ampliada sobre el conjunto del dataframe.

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Data columns (total 24 columns):
Case Number               5992 non-null object
Date                      5992 non-null object
Year                      5992 non-null int64
Type                      5992 non-null object
Country                   5949 non-null object
Area                      5590 non-null object
Location                  5496 non-null object
Activity                  5465 non-null object
Name                      5792 non-null object
Sex                       5425 non-null object
Age                       3311 non-null object
Injury                    5965 non-null object
Fatal (Y/N)               5973 non-null object
Time                      2779 non-null object
Species                   3058 non-null object
Investigator or Source    5977 non-null object
pdf                       5992 non-null object
href formula              5991 non-null object
href                      5989 non-null object
Case Number.1             5992 non-null object
Case Number.2             5992 non-null object
original order            5992 non-null int64
Unnamed: 22               1 non-null object
Unnamed: 23               2 non-null object
dtypes: int64(2), object(22)
memory usage: 1.1+ MB

In [7]:
# De primeras, vemos que hay algunas columnas que tienen relativamente pocos non-null valores.
# Por ejemplo destacan con pocos non-null values Age, Time, Species.

# Vemos también que una columna como Age está definida como object (string) en lugar de como numérico (int o float)

# Vemos también dos columnas que parecen extrañas, como son Unnamed:22 y Unnamed:23. Nombre raro y además solo tienen 1 y 2 valores respectivamente no nulos. Son columnas que no nos aportan nada, y eliminaremos posteriormente.
# Vemos también 3 columnas que parecen hacer referencia a lo mismo, como son Case Number, Case Number.1, Case Number.2. Las analizaremos más adelante porque a primera vista me hacen pensar que están repetidas.
# Iremos tratando cada columna de manera específica, comprendiendo qué es cada una y actuando como sea conveniente.

In [8]:
# Vamos a ver mejor el nombre de las columnas, por si hay espacios, carácteres especiales, etc.

data.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [9]:
# Vemos que 'Sex' y 'Species' tienen un espacio al final. Les cambiamos el nombre y lo ponemos bien.

data = data.rename(columns={'Sex ':'Sex','Species ':'Species'})
data.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [10]:
# Vamos a ver mejor cuántos nulls hay en cada columna

data.isnull().sum()

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

# Data Cleaning

**Vamos a ir explorando cada columna, cuáles podemos borrar por no ser útiles, cuáles tienen info duplicada, etc.**

In [11]:
# Hemos visto antes que especialmente Age, Time, Species tiene muchos valores nulos.
# Pero empezamos por Unnamed:22 y Unnamed:23, que prácticamente todos los valores son nulos.

**Columnas Unnamed:22 & Unnamed:23**

In [12]:
# Vamos a comprobar qué datos hay en las Unnamed:22 y Unnamed:23 y después borraremos estas columnas.

In [13]:
data['Unnamed: 22'].unique()

array([nan, 'stopped here'], dtype=object)

In [14]:
data['Unnamed: 23'].unique()

array([nan, 'Teramo', 'change filename'], dtype=object)

In [15]:
# No tienen ninguna información relevante, y todo el resto de valores son nulos. 
# Por tanto, eliminamos estas 2 columnas.
# Con axis = 1 hacemos referencia a que queremos borrar las columnas.

data = data.drop(['Unnamed: 22', 'Unnamed: 23'], axis=1)

**Columna Investigator or Source**

In [16]:
# Hay una columna que no me resulta demasiado útil en cuanto a la información que aporta.
# Se trata de 'Investigator or Source'. 
# Parece ser la persona que escribió cada informe, o la fuente de dónde se ha sacado la info.

# Vamos a ver exactamente cuáles son los valores únicos de esta columna, y decidimos si borrarla o no.

# Aquí al hacer el método unique() no me muestra todos los valores, porque son muchas rows. 
# Haré como alternativa un subset con esta columna, y luego head(50) para ver muestra de 50 registros.

investigator_subset = data['Investigator or Source']
investigator_subset.head(50)

0        Orlando Sentinel, 9/19/2016
1        Orlando Sentinel, 9/19/2016
2        Orlando Sentinel, 9/19/2016
3                 The Age, 9/18/2016
4                 The Age, 9/16/2016
5         West Australian, 9/15/2016
6                News4Jax, 9/11/2016
7          Hawaii News Now, 9/7/2016
8             TVANouvelles, 9/6/2016
9                  C. Creswell, GSAF
10               Perth Now, 9/5/2016
11        Orlando Sentinel, 9/7/2016
12                  R. Collier, GSAF
13           News Channel 8, 8/30/16
14           News Channel 8, 8/30/16
15              LaDepeche, 8/29/2016
16       First Coast News, 7/25/2016
17                    ABC, 8/11/2016
18                     SUP, 8/9/2015
19                News 965, 8/5/2016
20         Informacion.es, 7/29/2016
21               Klassick, 7/28/2016
22          ABC Australia, 7/28/2016
23        Tampa Bay Times, 7/27/2016
24    Gold Coast Bulletin, 7/28/2016
25            Japan Times, 7/25/2016
26                    C. Black, GSAF
27                   KWTX, 7/23/2016
28              Nine News, 7/20/2016
29                 Al.com, 7/19/2016
30       Orlando Sentinel, 7/21/2016
31       Orlando Sentinel, 7/21/2016
32                 C. Creswell, GSAF
33                GrindTV, 7/14/2016
34            La Opinion de Tenerife
35                  R. Collier, GSAF
36               Salem News 7/8/2016
37                  R. Collier, GSAF
38           Florida Today, 7/6/2016
39             Cairns Post, 7/9/2016
40                 C. Creswell, GSAF
41                 C. Creswell, GSAF
42                      Dr. A. Velez
43                News 24, 6/23/2016
44                 C. Creswell, GSAF
45          Florida Today, 6/22/2016
46      West Hawaii Today, 6/16/2016
47              Perth Now, 6/16/2016
48          Click2Houston, 6/14/2016
49                 C. Creswell, GSAF
Name: Investigator or Source, dtype: object

In [17]:
# Subset me confirma que es información poco importante. Borro esta columna del dataframe.

data = data.drop(['Investigator or Source'], axis=1)

**Columnas Case Number / Case Number.1 / Case Number.2**

In [18]:
# Vamos ahora con las 3 columnas de Case Number. 
# Hago un subset con ellas para verlas mejor.

casenumber_subset = data[['Case Number','Case Number.1','Case Number.2']]
casenumber_subset.head(50)

     Case Number Case Number.1 Case Number.2
0   2016.09.18.c  2016.09.18.c  2016.09.18.c
1   2016.09.18.b  2016.09.18.b  2016.09.18.b
2   2016.09.18.a  2016.09.18.a  2016.09.18.a
3     2016.09.17    2016.09.17    2016.09.17
4     2016.09.15    2016.09.16    2016.09.15
5   2016.09.15.R  2016.09.15.R  2016.09.15.R
6     2016.09.11    2016.09.11    2016.09.11
7     2016.09.07    2016.09.07    2016.09.07
8     2016.09.06    2016.09.06    2016.09.06
9   2016.09.05.b  2016.09.05.b  2016.09.05.b
10  2016.09.05.a  2016.09.05.a  2016.09.05.a
11    2016.09.04    2016.09.04    2016.09.04
12    2016.09.01    2016.09.01    2016.09.01
13  2016.08.29.b  2016.08.29.b  2016.08.29.b
14  2016.08.29.a  2016.08.29.a  2016.08.29.a
15    2016.08.27    2016.08.27    2016.08.27
16    2016.08.25    2016.08.25    2016.08.25
17    2016.08.07    2016.08.07    2016.08.07
18    2016.08.06    2016.08.06    2016.08.06
19    2016.08.04    2016.08.04    2016.08.04
20    2016.07.29    2016.07.29    2016.07.29
21  2016.07.28.R  2016.07.28.R  2016.07.28.R
22    2016.07.28    2016.07.28    2016.07.28
23    2016.07.27    2016.07.27    2016.07.27
24    2016.07.26    2016.07.26    2016.07.26
25    2016.07.24    2016.07.24    2016.07.24
26  2016.07.23.b  2016.07.23.b  2016.07.23.b
27  2016.07.23.a  2016.07.23.a  2016.07.23.a
28    2016.07.20    2016.07.20    2016.07.20
29    2016.07.17    2016.07.17    2016.07.17
30  2016.07.16.b  2016.07.16.b  2016.07.16.b
31  2016.07.16.a  2016.07.16.a  2016.07.16.a
32    2016.07.15    2016.07.15    2016.07.15
33  2016.07.14.4  2016.07.14.R  2016.07.14.4
34  2016.07.08.R  2016.07.08.R  2016.07.08.R
35    2016.07.08    2016.07.08    2016.07.08
36  2016.07.07.b  2016.07.07.b  2016.07.07.b
37  2016.07.07.a  2016.07.07.a  2016.07.07.a
38    2016.07.06    2016.07.06    2016.07.06
39    2016.07.04    2016.07.04    2016.07.04
40    2016.06.27    2016.06.27    2016.06.27
41    2016.06.25    2016.06.25    2016.06.25
42    2016.06.24    2016.06.24    2016.06.24
43    2016.06.23    2016.06.23    2016.06.23
44  2016.06.21.b  2016.06.21.b  2016.06.21.b
45  2016.06.21.a  2016.06.21.a  2016.06.21.a
46  2016.06.15.b  2016.06.15.b  2016.06.15.b
47  2016.06.15.a  2016.06.15.a  2016.06.15.a
48    2016.06.14    2016.06.14    2016.06.14
49    2016.06.11    2016.06.11    2016.06.11

In [19]:
# A simple vista, en los 50 primeros registros, parecen 3 columnas idénticas.
# Pero como son muchas rows, y 50 ejemplos serían pocos para confirmarlo, vamos a comparar primero Case Number con Case Number.1 y después Case Number con Case Number.2

# Para esta primera comparación, crearemos una nueva columna que será True si Case Number y Case Number.1 son iguales.
# Esta columna será False si son diferentes.

casenumber_subset['CN vs CN.1'] = casenumber_subset['Case Number'] == casenumber_subset['Case Number.1']
print(casenumber_subset['CN vs CN.1'])

0        True
1        True
2        True
3        True
4       False
        ...
5987     True
5988     True
5989     True
5990     True
5991     True
Name: CN vs CN.1, Length: 5992, dtype: bool

<ipython-input-19-7f44dc9c8b0e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  casenumber_subset['CN vs CN.1'] = casenumber_subset['Case Number'] == casenumber_subset['Case Number.1']

In [20]:
# Haremos lo mismo para comparar Case Number y Case Number.2

casenumber_subset['CN vs CN.2'] = casenumber_subset['Case Number'] == casenumber_subset['Case Number.2']
casenumber_subset['CN vs CN.2']

<ipython-input-20-0c17ba17e84f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  casenumber_subset['CN vs CN.2'] = casenumber_subset['Case Number'] == casenumber_subset['Case Number.2']

0       True
1       True
2       True
3       True
4       True
        ...
5987    True
5988    True
5989    True
5990    True
5991    True
Name: CN vs CN.2, Length: 5992, dtype: bool

In [21]:
# Vamos a contar cuántos True (es decir, repetidos) hay en ['CN vs CN.1']

casenumber_subset['CN vs CN.1'].value_counts()

True     5979
False      13
Name: CN vs CN.1, dtype: int64

In [22]:
# Vamos a contar cuántos True (es decir, repetidos) hay en ['CN vs CN.2']

casenumber_subset['CN vs CN.2'].value_counts()

True     5990
False       2
Name: CN vs CN.2, dtype: int64

In [23]:
# Es decir, CN vs CN.1 es True (se repite) 5979 veces, de un total de 5992. Se puede considerar duplicada.
# Por su lado, CN vs CN.2 es True (se repite) 5990 veces, de un total de 5992. Se puede considerar duplicada.

# Eliminamos por tanto de nuestro dataframe tanto Case Number.1 como Case Number.2

data = data.drop(['Case Number.1', 'Case Number.2'], axis=1)

**Columna Original Order**

In [24]:
# Otra columna que no parece aportar una información relevante es "Original Order"
# Vamos a ver qué es esta columna.

data['original order'].value_counts().head(50)

5661    2
569     2
3847    2
5739    2
2047    1
2716    1
4755    1
2708    1
661     1
4759    1
2712    1
665     1
4763    1
4767    1
669     1
2704    1
2720    1
673     1
4771    1
2724    1
677     1
4775    1
2728    1
657     1
4751    1
4779    1
4735    1
4723    1
2676    1
629     1
4727    1
2680    1
633     1
4731    1
2684    1
637     1
2688    1
653     1
641     1
4739    1
2692    1
645     1
4743    1
2696    1
649     1
4747    1
2700    1
681     1
2732    1
2672    1
Name: original order, dtype: int64

In [25]:
# Parece ser una especie de índice o de numeración de cada row, no parece relevante. Lo borramos.

data = data.drop(['original order'], axis=1)

**Columna Name**

In [26]:
# Otra columna que no me parece importante, es la de Name. 
# No influye en nada el nombre de la persona que ha sido atacada.
# Por tanto, borro la columna de name también.

data = data.drop(['Name'], axis=1)

**Columnas pdf / href / href formula**

In [27]:
# Vamos a revisar ahora las columnas, 'pdf', href' y 'href formula' porque parecen iguales o muy parecidas.
# Por el valor de cada columna, parecen documentos .pdf que guardan el informe de cada ataque.

document_subset = data[['pdf','href','href formula']]
document_subset.head(50)

,pdf,href,href formula
0,2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5,2016.09.15.R-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
6,2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
7,2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
8,2016.09.06-Jewell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
9,2016.09.05.b-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
10,2016.09.05.a-Penman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
11,2016.09.04-Moore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
12,2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
13,2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
14,2016.08.29.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
15,2016.08.27-Chardard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
16,2016.08.25-Cassetty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
17,2016.08.07-Stoch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
18,2016.08.06-Baxter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
19,2016.06.04-Tyler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
20,2016.07.29-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
21,2016.07.28.R-Franz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
22,2016.07.28-Watkins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
23,2016.07.27-Sapp.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
24,2016.07.26-Ballina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
25,2016.07.24-Japan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
26,2016.07.23.b-Critchlow.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
27,2016.07.23.a-Cutbirth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
28,2016.07.20-Burck.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
29,2016.07.17-Gulf.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
30,2016.07.16.b-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
31,2016.07.16.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
32,2016.07.14-MyrtleBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
33,2016.07.14.R-TigerBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
34,2016.07.08.R-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
35,2016.07.08-CapitolaBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
36,2016.07.07.b-Brissom.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
37,2016.07.07.a-PoeBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
38,2016.07.06-Njwoman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
39,2016.07.04-Oliver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
40,2016.06.27-Sullivans.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
41,2016.06.25-AtlanticBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
42,2016.06.24-Velez.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
43,2016.06.23-Rysport.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
44,2016.06.21.b-Schott.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
45,2016.06.21.a-SatelliteBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
46,2016.06.15.b-Kauai.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
47,2016.06.15.a-Vale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
48,2016.06.14-Melton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
49,2016.06.11-Bowen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [28]:
# Nuevamente, podríamos hacer como con Case Number y comparar cada registro para ver si son repetidos o no.
# Sin embargo, el objetivo de nuestro análisis es limpiar la base de datos de tal forma que nos permita sacar conclusiones o nos desvele información sobre los ataques de tiburón.

# Por tanto, en este caso creo que no es importante tener columnas que nos hagan referencia a los informes .pdf.
# Eliminaremos estas columnas, porque dan información que en nuestro análisis no es necesaria.

data = data.drop(['pdf', 'href', 'href formula'], axis=1)

In [29]:
# Vamos a hacer un resumen de cómo tenemos ahora la tabla tras lo que hemos ido eliminando.

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Data columns (total 14 columns):
Case Number    5992 non-null object
Date           5992 non-null object
Year           5992 non-null int64
Type           5992 non-null object
Country        5949 non-null object
Area           5590 non-null object
Location       5496 non-null object
Activity       5465 non-null object
Sex            5425 non-null object
Age            3311 non-null object
Injury         5965 non-null object
Fatal (Y/N)    5973 non-null object
Time           2779 non-null object
Species        3058 non-null object
dtypes: int64(1), object(13)
memory usage: 655.5+ KB

**Columna Time**

In [30]:
# Vemos que "Time" tiene una gran cantidad de nulls.

time_subset = data['Time']
time_subset.head(50)

0              13h00
1              11h00
2              10h43
3                NaN
4                NaN
5                NaN
6              15h15
7              14h30
8              15h40
9     Late afternoon
10    Late afternoon
11               NaN
12               NaN
13             15h00
14             14h00
15             17h00
16             16h00
17               NaN
18               NaN
19               NaN
20             11h30
21               NaN
22               NaN
23               NaN
24             12h00
25             19h05
26               NaN
27               NaN
28        After noon
29               NaN
30              1300
31             11h00
32               NaN
33               NaN
34               NaN
35               NaN
36             10h00
37               NaN
38     14h30 / 15h30
39             22h00
40             16h20
41             14h34
42             11h00
43               NaN
44             15h25
45             14h55
46             06h00
47               NaN
48             17h30
49             15h00
Name: Time, dtype: object

**Columna Date**

In [31]:
# Tanto con Date como con Time, me hubiera gustado poder agruparlos de alguna manera.
# Por ejemplo con Time haber separado momentos del día (Morning, Afternoon, Evening) pero no he conseguido saber hacerlo.
# Con Date, lo mismo. He intentado darles algún sentido agrupándolo por meses. Pero no me ha salido.
# Pendiente de preguntar a TA tras la correción.

# Por tanto, lo que hago con Date y Time es borrarlos como columna. Me centraré en Year de cara a situar en el tiempo los ataques.

data = data.drop(['Date','Time'], axis=1)

**Columna Year**

In [32]:
# Vamos con la columna Year. 
# Convertiré todas las entradas a valor numérico, y las que no se puedan me devolverá NaN (al indicar errors='coerce')

data['Year'] = pd.to_numeric(data['Year'], errors='coerce')
data['Year'].value_counts().head(50)

2015    139
2011    128
2014    125
0       124
2013    122
2008    121
2009    120
2012    117
2007    112
2006    103
2016    103
2005    103
2010    101
2000     97
1959     93
1960     93
2001     92
2004     92
2003     92
2002     88
1962     86
1961     78
1995     76
1964     66
1998     65
1999     65
1996     61
1963     61
1966     58
1997     57
1993     56
1994     56
1992     56
1988     55
1958     54
1989     53
1956     51
1965     51
1983     50
1975     49
1981     49
1967     48
1968     46
1950     43
1955     43
1954     42
1970     42
1957     41
1984     41
1942     41
Name: Year, dtype: int64

**Columna Age**

In [33]:
# Exploramos ahora la columna Age.
# Vemos que Age tiene "pocos" valores non-null (es decir, "muchos" nulls)
# Además está como object en lugar de como valor numérico.
# Lo tendremos que convertir también a valor numérico.

# Exploramos primero los valores de la columna Age

data['Age'].value_counts()

17             148
18             145
19             138
20             136
15             135
              ...
73               1
mid-30s          1
9 months         1
28, 23 & 30      1
72               1
Name: Age, Length: 151, dtype: int64

In [34]:
# Pasamos el valor a numérico. 
# Nuevamnete, al indicar errors='coerce' insertamos NaN en aquellos valores que no se puedan convertir a número.

data['Age'] = pd.to_numeric(data['Age'], errors='coerce')
data['Age'].value_counts()

17.0    148
18.0    145
19.0    138
20.0    136
15.0    135
       ...
84.0      1
87.0      1
67.0      1
86.0      1
81.0      1
Name: Age, Length: 79, dtype: int64

In [35]:
# Vamos a ver si hay algún valor de edad desproporcionado que pueda tratarse de un error. 
# Vemos que la máxima edad es 87 años, lo cual es posible, así que damos por bueno el conjunto de edades.

data['Age'].max()

87.0

**Columna Species**

In [36]:
# Vamos ahora con la columna de 'Species' que también nos indicaba que tenía muchos valores null.

data['Species'].value_counts()

White shark                                     161
Shark involvement not confirmed                  80
Tiger shark                                      68
Bull shark                                       52
6' shark                                         40
                                               ...
Dusky shark, 3m                                   1
Nurse shark, 1.1 m [3.5']                         1
Shovelnose guitarfish, adult male                 1
Unknown                                           1
Oceanic whitetip sharks were in the vicinity      1
Name: Species, Length: 1538, dtype: int64

In [37]:
# Parece un campo donde hay información muy variada, descripciones largas, con muchas palabras
# Las especies "mejor definidas" sería White shark, Tiger shark, Bull shark, pero en el mejor de los casos se define bien 161 veces.
# Considero que 161 veces como mejor clasificación es insignificante respecto a 5992 rows que tenemos.
# Por tanto, borro esta columna de Species.

data = data.drop(['Species'], axis=1)

**Columna Sex**

In [38]:
# Vamos a explorar la columna Sex

data['Sex'].value_counts()

M      4835
F       585
M         2
lli       1
.         1
N         1
Name: Sex, dtype: int64

In [39]:
# Hay algunos que están mal introducidos, los vamos a cambiar por "Unknow"

data['Sex'] = data['Sex'].replace(['lli', 'N', '.', 'M '], 'Unknow')

In [40]:
# Obtenemos 4835 registros que son Male (Hombres) y 585 que son Female (Mujeres)
# 5 registros son Unknow

data['Sex'].value_counts()

M         4835
F          585
Unknow       5
Name: Sex, dtype: int64

**Columna Fatal**

In [41]:
# Exploramos ahora la columna 'Fatal (Y/N)' que indica si el ataque ha sido mortal o no.

data['Fatal (Y/N)'].value_counts()

N          4315
Y          1552
UNKNOWN      94
 N            8
N             1
#VALUE!       1
n             1
F             1
Name: Fatal (Y/N), dtype: int64

In [42]:
# Hay algunos que están mal introducidos, los corregimos.

data['Fatal (Y/N)'] = data['Fatal (Y/N)'].replace([' N', 'n', 'N '], 'N')
data['Fatal (Y/N)'] = data['Fatal (Y/N)'].replace(['#VALUE!', 'F'], 'UNKNOWN')

In [43]:
# Nos encontramos con 4325 casos NO MORTALES, con 1552 casos MORTALES, y con 96 con resultado desconocido.
data['Fatal (Y/N)'].value_counts()

N          4325
Y          1552
UNKNOWN      96
Name: Fatal (Y/N), dtype: int64

**Columna Country**

In [44]:
# Vamos a explorar ahora la columna Country

data['Country'].unique()

array(['USA', 'AUSTRALIA', 'NEW CALEDONIA', 'REUNION', 'BAHAMAS', 'SPAIN',
       'CHINA', 'JAPAN', 'COLUMBIA', 'SOUTH AFRICA', 'EGYPT',
       'NEW ZEALAND', 'INDONESIA', 'FRENCH POLYNESIA', 'CAPE VERDE',
       'Fiji', 'BRAZIL', 'DOMINICAN REPUBLIC', 'CAYMAN ISLANDS',
       'UNITED ARAB EMIRATES', 'ARUBA', 'MOZAMBIQUE', 'THAILAND', 'FIJI',
       'PUERTO RICO', 'ITALY', 'MEXICO', 'ATLANTIC OCEAN', 'GREECE',
       'MAURITIUS', nan, 'ST. MARTIN', 'FRANCE', 'ECUADOR',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'PHILIPPINES', 'NIGERIA', 'TONGA',
       'SCOTLAND', 'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE',
       'ANTIGUA', 'KENYA', 'RUSSIA', 'TURKS & CAICOS', 'COSTA RICA',
       'UNITED KINGDOM', 'MALAYSIA', 'UNITED ARAB EMIRATES (UAE)',
       'SAMOA', 'AZORES', 'SOLOMON ISLANDS', 'SOUTH KOREA', 'MALTA',
       'VIETNAM', 'MADAGASCAR', 'PANAMA', 'SOMALIA', 'NEVIS', 'CUBA',
       'ENGLAND', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL', 'YEMEN',
       'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN', 'GRAND CAYMAN',
       'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ', 'HONDURAS',
       'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
       'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', 'SIERRA LEONE',
       ' PHILIPPINES', 'NICARAGUA', 'CENTRAL PACIFIC',
       'SOLOMON ISLANDS / VANUATU', 'SOUTHWEST PACIFIC OCEAN',
       'BAY OF BENGAL', 'MID-PACIFC OCEAN', 'SLOVENIA', 'CURACAO',
       'ITALY / CROATIA', 'BARBADOS', 'MONACO', 'GUYANA', 'HAITI',
       'SAN DOMINGO', 'IRELAND', 'KUWAIT', 'LIBYA', 'YEMEN ',
       'MEDITERRANEAN SEA?', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS',
       'EGYPT ', 'BURMA', 'LEBANON', 'PARAGUAY', 'BRITISH NEW GUINEA',
       'OCEAN', 'GEORGIA', 'SYRIA', 'TUVALU', 'INDIAN OCEAN?', 'GUINEA',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'ALGERIA',
       'Coast of AFRICA', 'TASMAN SEA', 'GHANA', 'St Helena', 'GREENLAND',
       'MEDITERRANEAN SEA', 'SWEDEN', 'ICELAND',
       'Between PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA',
       'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [45]:
# Veo que no todos están correctamente escritos.

# Unifico por ejemplo todos a mayúsculas

data['Country'] = data['Country'].str.upper()

In [46]:
# Veo que algunas entradas acaban en signo de interrogación. Se lo quito.

data['Country'] = data['Country'].replace(['?',' '])

In [47]:
# Reviso el nuevo conjunto de países tras la limpieza.

data['Country'].unique()

array(['USA', 'AUSTRALIA', 'NEW CALEDONIA', 'REUNION', 'BAHAMAS', 'SPAIN',
       'CHINA', 'JAPAN', 'COLUMBIA', 'SOUTH AFRICA', 'EGYPT',
       'NEW ZEALAND', 'INDONESIA', 'FRENCH POLYNESIA', 'CAPE VERDE',
       'FIJI', 'BRAZIL', 'DOMINICAN REPUBLIC', 'CAYMAN ISLANDS',
       'UNITED ARAB EMIRATES', 'ARUBA', 'MOZAMBIQUE', 'THAILAND',
       'PUERTO RICO', 'ITALY', 'MEXICO', 'ATLANTIC OCEAN', 'GREECE',
       'MAURITIUS', nan, 'ST. MARTIN', 'FRANCE', 'ECUADOR',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'PHILIPPINES', 'NIGERIA', 'TONGA',
       'SCOTLAND', 'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE',
       'ANTIGUA', 'KENYA', 'RUSSIA', 'TURKS & CAICOS', 'COSTA RICA',
       'UNITED KINGDOM', 'MALAYSIA', 'UNITED ARAB EMIRATES (UAE)',
       'SAMOA', 'AZORES', 'SOLOMON ISLANDS', 'SOUTH KOREA', 'MALTA',
       'VIETNAM', 'MADAGASCAR', 'PANAMA', 'SOMALIA', 'NEVIS', 'CUBA',
       'ENGLAND', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL', 'YEMEN',
       'GULF OF ADEN', 'SIERRA LEONE', 'ST. MAARTIN', 'GRAND CAYMAN',
       'LIBERIA', 'VANUATU', 'MEXICO ', 'HONDURAS', 'VENEZUELA',
       'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA', 'MICRONESIA',
       'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA', 'MARSHALL ISLANDS',
       'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA', 'HONG KONG',
       'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO', 'IRAN',
       'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN', 'PORTUGAL',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'ARGENTINA',
       'MARTINIQUE', 'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', ' PHILIPPINES',
       'NICARAGUA', 'CENTRAL PACIFIC', 'SOLOMON ISLANDS / VANUATU',
       'SOUTHWEST PACIFIC OCEAN', 'BAY OF BENGAL', 'MID-PACIFC OCEAN',
       'SLOVENIA', 'CURACAO', 'ITALY / CROATIA', 'BARBADOS', 'MONACO',
       'GUYANA', 'HAITI', 'SAN DOMINGO', 'IRELAND', 'KUWAIT', 'LIBYA',
       'YEMEN ', 'MEDITERRANEAN SEA?', 'FALKLAND ISLANDS', 'CRETE',
       'CYPRUS', 'EGYPT ', 'BURMA', 'LEBANON', 'PARAGUAY',
       'BRITISH NEW GUINEA', 'OCEAN', 'GEORGIA', 'SYRIA', 'TUVALU',
       'INDIAN OCEAN?', 'GUINEA', 'EQUATORIAL GUINEA / CAMEROON',
       'COOK ISLANDS', 'ALGERIA', 'COAST OF AFRICA', 'TASMAN SEA',
       'GHANA', 'ST HELENA', 'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN',
       'ICELAND', 'BETWEEN PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN',
       'KOREA', 'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [48]:
# Vemos como Estados Unidos y Australia son los países que tienen más ataques. Seguidos de South Africa.
data['Country'].value_counts()

USA                 2116
AUSTRALIA           1279
SOUTH AFRICA         565
PAPUA NEW GUINEA     133
NEW ZEALAND          125
                    ...
GULF OF ADEN           1
TUVALU                 1
MONACO                 1
MALDIVE ISLANDS        1
GREENLAND              1
Name: Country, Length: 200, dtype: int64

**Columna Location**

In [49]:
data['Location'].value_counts().head(50)

New Smyrna Beach, Volusia County                   157
Daytona Beach, Volusia County                       28
Myrtle Beach, Horry County                          17
Ponce Inlet, Volusia County                         17
Durban                                              15
Melbourne Beach, Brevard County                     15
Isle of Palms, Charleston County                    14
Boa Viagem, Recife                                  13
Cocoa Beach, Brevard County                         12
Ponce Inlet, New Smyrna Beach, Volusia County       12
Mossel Bay                                          11
Palm Beach, Palm Beach County                       11
Ahvaz, on the Karun River                           11
Cocoa Beach, Brevard  County                        10
Piedade                                             10
Xai Xai                                             10
Singer Island, Riviera Beach, Palm Beach County     10
Sydney Harbor                                       10
Sydney                                              10
Nahoon                                              10
Ormond Beach, Volusia County                        10
Near Thursday Island                                 9
Florida Keys, Monroe County                          9
Boa Viagem Beach, Recife                             9
Brisbane River                                       9
Nahoon, East London                                  9
North Beach, Durban                                  9
Jacksonville Beach, Duval County                     9
Florida Keys                                         8
False Bay                                            8
Country Club Beach, Durban                           8
Juno Beach, Palm Beach County                        8
Amanzimtoti                                          8
Quy Nhon                                             8
Sanibel Island, Lee County                           8
Thursday Island                                      8
Bunbury                                              7
Jacksonville, Duval County                           7
Havana Harbor                                        7
Moreton Bay                                          7
Riviera Beach, Palm Beach County                     7
Vero Beach, Indian River County                      7
Port Alfred                                          7
Port Said                                            7
Plettenberg Bay                                      7
Ross River, Townsville                               7
Brisbane                                             6
Panama City, Bay County                              6
Wollongong                                           6
Jupiter, Palm Beach County                           6
Name: Location, dtype: int64

In [50]:
# Respecto a la columna de Location, aparecen muchos valores muy diversos y no aportan una gran información agrupada.
# Será una columna que borro. Nos centraremos más en Country de cara a localizar los ataques.

data = data.drop(['Location','Area'], axis=1)

In [51]:
# Con la tabla que nos va quedando, considero que puede ser interesante un análisis en el que tengamos veamos
# una relación entre los países donde se producen más ataques, así como de las Activity que tienen mayor riesgo 
# y si son ataques mortales o no. Nos fijaremos en los datos que tenemos desde 1900 hasta ahora.

# Por otro lado, también es interesante fijarnos en los datos que tenemos para conocer cómo se reparten
# los ataques según Hombres / Mujeres y rangos de edades.

# Quito por tanto 'Type' e 'Injury' ya que no las usaremos en nuestros análisis.
data = data.drop(['Type', 'Injury'], axis=1)

In [52]:
# Vamos a delimitar nuestro DataFrame para aquellos registros que tenemos a partir de 1900.

data = data[data.Year > 1900]

**Eliminación rows duplicadas**

In [53]:
before = len(data) # Cuántos rows eran antes.
data = data.drop_duplicates()

after = len(data) # Cuántos rows quedan después de eliminar duplicates.

print ('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  1

# Dataframe Cleaned

In [54]:
# Vamos a ver cómo queda el dataframe con las columnas limpiadas y eliminadas.

data_clean = data

data_clean.head(10)

    Case Number  Year        Country         Activity  Sex   Age Fatal (Y/N)
0  2016.09.18.c  2016            USA          Surfing    M  16.0           N
1  2016.09.18.b  2016            USA          Surfing    M  36.0           N
2  2016.09.18.a  2016            USA          Surfing    M  43.0           N
3    2016.09.17  2016      AUSTRALIA          Surfing    M   NaN           N
4    2016.09.15  2016      AUSTRALIA          Surfing    M   NaN           N
5  2016.09.15.R  2016      AUSTRALIA          Fishing  NaN   NaN           N
6    2016.09.11  2016            USA           Wading    M   NaN           N
7    2016.09.07  2016            USA         Swimming    F  51.0           N
8    2016.09.06  2016  NEW CALEDONIA     Kite surfing    M  50.0           Y
9  2016.09.05.b  2016            USA  Boogie boarding    F  12.0           N

# Dataframe Cleaned to CSV Cleaned

In [55]:
# Pasamos nuestro dataframe limpio a un nuevo archivo CSV cleaned.

data_clean.to_csv("data_clean.csv")

# Dataframe Análisis & Conclusiones

**Con la información que hemos limpiado y nos queda en nuestro dataframe, vamos a sacar algunas conclusiones.**

## Número de ataques por rango de edades

In [56]:
# Vamos a agrupar por rangos de edades

age_labels = ['Niños (<18años)', 'Jóvenes (18-30 años)', 'Adultos (31-60)', 'Mayores (>61 años)']

cutoffs = [19,31,61,66]

data['Rango Edad'] = pd.cut(data['Age'],4 , labels=age_labels)

data.head()

,Case Number,Year,Country,Activity,Sex,Age,Fatal (Y/N),Rango Edad
0,2016.09.18.c,2016,USA,Surfing,M,16.0,N,Niños (<18años)
1,2016.09.18.b,2016,USA,Surfing,M,36.0,N,Jóvenes (18-30 años)
2,2016.09.18.a,2016,USA,Surfing,M,43.0,N,Jóvenes (18-30 años)
3,2016.09.17,2016,AUSTRALIA,Surfing,M,NaN,N,NaN
4,2016.09.15,2016,AUSTRALIA,Surfing,M,NaN,N,NaN

In [57]:
# Vamos a ver cuántos ataques de tiburón hay para cada rango de edad.

data_per_age = data.groupby(['Rango Edad']).size()
data_per_age

Rango Edad
Niños (<18años)         1458
Jóvenes (18-30 años)    1262
Adultos (31-60)          362
Mayores (>61 años)        42
dtype: int64

**Desde 1900 el mayor número de ataques se sitúa en Niños < 18 años y Jóvenes de 18-30 años.**

In [58]:
# Lo vamos a mostrar como porcentaje, para que sea más significativo.

data_per_age.sum()

3124

In [59]:
data_per_age/data_per_age.sum()*100

Rango Edad
Niños (<18años)         46.670935
Jóvenes (18-30 años)    40.396927
Adultos (31-60)         11.587708
Mayores (>61 años)       1.344430
dtype: float64

**El 47% de ataques es a personas menores de 18 años, y el 40% a personas entre 18 y 30 años**

## Información extra respecto a Age - Media de Edad a los que se sufre los ataques.

In [60]:
# Como información complementaria que podemos obtener de la columna Age, tendriamos que:

data['Age'].describe()

count    3124.000000
mean       27.292254
std        13.762686
min         1.000000
25%        17.000000
50%        24.000000
75%        35.000000
max        87.000000
Name: Age, dtype: float64

**La media de edad a la que se sufren los ataques es a los 27 años.**

**La edad más alta que se tiene registro de ataque de tiburón es a los 87 años.**

**La menor, a 1 año de edad.**

## Análisis de ataques por Hombre / Mujer

In [61]:
# Vamos a hacer algo similar para diferenciar entre ataques a Hombres y Mujeres.

data['Sex'].value_counts()

M         4253
F          548
Unknow       5
Name: Sex, dtype: int64

In [62]:
data['Sex'].value_counts().sum()

4806

In [63]:
(data['Sex'].value_counts() / data['Sex'].value_counts().sum())*100

M         88.493550
F         11.402414
Unknow     0.104037
Name: Sex, dtype: float64

**El 89% de ataques se produce a Male (Hombres) y un 11% de ataques es a Female (mujeres)**

In [64]:
# Y ahora, vamos a combinar cuál es la media de edad a la que Hombres y Mujeres sufren los ataques.

avg_age_sex = data.groupby('Sex', as_index = False)['Age'].mean()

avg_age_sex

      Sex        Age
0       F  26.700748
1       M  27.403052
2  Unknow  40.000000

In [65]:
# En ambos casos, la media de edad a la que se sufre el ataque es similar.
# 26 años en mujeres, 27 años en Hombres.

## Número de ataques por Activity

In [66]:
# Vamos a explorar ahora la columna de Activity y cuántos ataques se sufren por cada tipo de actividad.

data['Activity'].value_counts().head(3)

Surfing     900
Swimming    711
Fishing     366
Name: Activity, dtype: int64

**Las 3 actividades que más ataques sufren son Surfing, Swimming y Fishing.**

In [67]:
# Número de ataques por Country

In [68]:
data['Country'].value_counts()

USA                     1985
AUSTRALIA               1121
SOUTH AFRICA             532
PAPUA NEW GUINEA         129
BRAZIL                   100
                        ...
ST. MARTIN                 1
ARUBA                      1
NICARAGUA                  1
ANTIGUA                    1
NETHERLANDS ANTILLES       1
Name: Country, Length: 171, dtype: int64

In [69]:
data['Country'].value_counts().head(3)

USA             1985
AUSTRALIA       1121
SOUTH AFRICA     532
Name: Country, dtype: int64

**Los 3 países que más ataques tienen de tiburones son USA, Australia y South Africa**